update: wrap echo with compose_log

diff --git a/compose-cd b/compose-cd
--- a/compose-cd
+++ b/compose-cd
@@ -108,9 +108,9 @@ function load_global_config() {
 }
 
 function load_config() {
-	echo -n "[$proj:load config] "
+	compose_log echo -n "[$proj:load config] "
 	if [ ! -e ./.compose-cd ]; then
-		echo "config file not found"
+		compose_log echo "config file not found"
 		return
 	fi
 	# shellcheck disable=SC1091
@@ -123,15 +123,15 @@ function load_config() {
 	if [ -z ${PRIVATE_IMAGE+x} ]; then PRIVATE_IMAGE=false; fi
 
 	if "$UPDATE_REPO_ONLY" && "$UPDATE_IMAGE_ONLY"; then
-		echo "UPDATE_REPO_ONLY and UPDATE_IMAGE_ONLY are true. This is something wrong."
+		compose_log echo "UPDATE_REPO_ONLY and UPDATE_IMAGE_ONLY are true. This is something wrong."
 		exit 1
 	fi
 	if "$UPDATE_IMAGE_ONLY" && "$UPDATE_IMAGE_BY_REPO"; then
-		echo "UPDATE_IMAGE_ONLY and UPDATE_IMAGE_BY_REPO are true. This is something wrong."
+		compose_log echo "UPDATE_IMAGE_ONLY and UPDATE_IMAGE_BY_REPO are true. This is something wrong."
 		exit 1
 	fi
 
-	echo "ok"
+	compose_log echo "ok"
 }
 
 function service_up() {
@@ -186,18 +186,18 @@ function get_remote_image() {
 
 	#echo $registry_token
 
-	echo -n "${tag} "
+	compose_log echo -n "${tag} "
 	manifest=$(curl --silent \
 		--header "Accept: application/vnd.docker.distribution.manifest.v2+json" \
 		--header "Authorization: Bearer ${registry_token}" \
 		"https://${registry}/v2/${image}/manifests/${tag}")
 
 	if echo "${manifest}" | grep 'errors'; then
-		echo "${manifest}" 1>&2
+		compose_log echo "${manifest}" 1>&2
 		exit 1
 	fi
 
-	echo "${manifest}" | jq -r '.config.digest'
+	compose_log echo "${manifest}" | jq -r '.config.digest'
 }
 
 function git() {
@@ -214,7 +214,7 @@ function update_repo() {
 	local apply_list_expand
 	local is_restart
 
-	echo -n "[$project:update repository] "
+	compose_log echo -n "[$project:update repository] "
 
 	branch=$(git symbolic-ref --short HEAD)
 	local_commit=$(git rev-parse HEAD)
@@ -222,17 +222,17 @@ function update_repo() {
 
 	if [ -z "$remote_commit" ]; then
 		compose_log notify "error: could not get remote commit"
-		echo "branch: ${branch}"
+		compose_log echo "branch: ${branch}"
 		return 2
 	fi
 
 	if [[ $local_commit = "$remote_commit" ]]; then
 		# no update
-		echo "pass"
+		compose_log echo "pass"
 		return 1
 	fi
 
-	echo "pull start"
+	compose_log echo "pull start"
 	local local_commit_link
 	local remote_commit_link
 	local_commit_link="[$local_commit]($(git remote get-url origin)/commit/${local_commit})"
@@ -294,23 +294,23 @@ function update_image() {
 	local remote_img
 	local remote_img_id
 
-	echo -n "[$project:update image] "
+	compose_log echo -n "[$project:update image] "
 
 	if [ -z ${REGISTRY+x} ]; then
-		echo "error: REGISTRY is not set"
+		compose_log echo "error: REGISTRY is not set"
 		return
 	fi
 	if [ -z ${IMAGE+x} ]; then
-		echo "error: REGISTRY is not set"
+		compose_log echo "error: REGISTRY is not set"
 		return
 	fi
 	img_location="${REGISTRY}/${IMAGE}" # like ghcr.io/sksat/kuso-subdomain-adder
 
 	if [ -z ${IMG_TAG+x} ]; then
-		echo "warning: IMG_TAG is not set"
+		compose_log echo "warning: IMG_TAG is not set"
 		img_tag="main"
 
-		echo -n "[$project:update image] "
+		compose_log echo -n "[$project:update image] "
 	else
 		img_tag="${IMG_TAG}"
 	fi
@@ -325,25 +325,25 @@ function update_image() {
 	remote_img=$(get_remote_image "${REGISTRY}" "${IMAGE}" "${img_tag}")
 	remote_img_id=$(cut -d' ' -f 2 <<<"${remote_img}")
 
-	echo "remote_img_id: ${remote_img_id}"
+	compose_log echo "remote_img_id: ${remote_img_id}"
 	if echo "${remote_img}" | grep -q 'null' || [ "$remote_img_id" = "" ]; then
 		compose_log notify "error: remote image is null!" ""
-		echo "registry: ${REGISTRY}"
-		echo "image: ${IMAGE}"
-		echo "tag: ${img_tag}"
+		compose_log echo "registry: ${REGISTRY}"
+		compose_log echo "image: ${IMAGE}"
+		compose_log echo "tag: ${img_tag}"
 		return 2
 	fi
 
 	if [[ $local_img = "$remote_img" ]]; then
 		# no update
-		echo "pass"
+		compose_log echo "pass"
 		return 1
 	fi
 
-	echo "pull start"
+	compose_log echo "pull start"
 	compose_log notify "update image: ${local_img} ===> ${remote_img}"
 	docker-compose pull --quiet
-	echo "[$project:update image] done"
+	compose_log echo "[$project:update image] done"
 }
 
 function project_update() {
@@ -369,7 +369,7 @@ function project_update() {
 
 	# no update
 	if [ $rr = 1 ] && [ $ri = 1 ]; then
-		echo "no update"
+		compose_log echo "no update"
 		return
 	fi
 
@@ -399,7 +399,7 @@ function project_update() {
 
 	# todo: running check
 
-	echo "restart service..."
+	compose_log echo "restart service..."
 	service_down
 	service_up
 
@@ -415,13 +415,13 @@ function project_status() {
 
 	proj=$1
 
-	echo -n "[$proj:status] "
+	compose_log echo -n "[$proj:status] "
 	services=$(docker-compose ps -q)
 
 	if [ -n "$services" ]; then
-		echo "up"
+		compose_log echo "up"
 	else
-		echo "down"
+		compose_log echo "down"
 	fi
 }
 
@@ -430,7 +430,7 @@ function foreach_project() {
 	local cfgs
 
 	if [ -z ${SEARCH_ROOT+x} ]; then
-		echo "error: SEARCH_ROOT is not set"
+		compose_log echo "error: SEARCH_ROOT is not set"
 		return
 	fi
 	search_root=${SEARCH_ROOT}
@@ -438,7 +438,7 @@ function foreach_project() {
 	# execute in subshell
 	(
 		cd "${search_root}" || {
-			echo "error: SEARCH_ROOT(${search_root}) not found"
+			compose_log echo "error: SEARCH_ROOT(${search_root}) not found"
 			exit 1
 		}
 		cfgs=$(find . -maxdepth 5 -type f -name '.compose-cd')
@@ -449,7 +449,7 @@ function foreach_project() {
 
 			(
 				cd "$proj" || {
-					echo "[$proj] error: project not fouund"
+					compose_log echo "[$proj] error: project not fouund"
 					exit 1
 				}
 				eval "$1 $proj"
@@ -549,21 +549,21 @@ function uninstall() {
 }
 
 function check_status() {
-	echo "check status"
+	compose_log echo "check status"
 
 	load_global_config
 	foreach_project project_status
 }
 
 function update() {
-	echo "update"
+	compose_log echo "update"
 
 	load_global_config
 	foreach_project project_update
 }
 
 function cleanup() {
-	echo "cleanup: container images"
+	compose_log echo "cleanup: container images"
 	docker image prune -a -f
 }
 
