feat: parse arguments passed to install command

diff --git a/compose-cd b/compose-cd
--- a/compose-cd
+++ b/compose-cd
@@ -401,12 +401,45 @@ function foreach_project() {
 function install() {
 	echo "install"
 
-	read -rp "search root> " SEARCH_ROOT
-	read -rp "git pull user> " GIT_PULL_USER
-	read -rp "Discord webhook URL> " DISCORD_WEBHOOK
+	local search_root
+	local git_pull_user
+	local discord_webhook
+
+	# We only have options with single parameter, so
+	# parse options while there are more than 1 unparsed arguments
+    while [[ $# -gt 1 ]]; do
+		case $1 in
+			--search-root|-s)
+				search_root="$2"
+				shift
+				shift
+				;;
+			--git-pull-user|-g)
+				git_pull_user="$2"
+				shift
+				shift
+				;;
+			--discord-webhook|-d)
+				discord_webhook="$2"
+				shift
+				shift
+				;;
+			*)
+				echo "Error: unknown option: $1"
+				exit 1
+		esac
+	done
+	if [[ $# -gt 0 ]]; do
+		echo "Error: expected a parameter for option: $1"
+		exit 1
+	fi
+
+	if [ -z ${search_root+x} ]; then read -rp "search root> " search_root; fi
+	if [ -z ${git_pull_user+x} ]; then read -rp "git pull user> " git_pull_user; fi
+	if [ -z ${discord_webhook+x} ]; then read -rp "Discord webhook URL> " discord_webhook; fi
 
 	mkdir -p /etc/compose-cd
-	echo -e "SEARCH_ROOT=\"${SEARCH_ROOT}\"\n\nGIT_PULL_USER=\"${GIT_PULL_USER}\"\n\nDISCORD_WEBHOOK=\"${DISCORD_WEBHOOK}\"" | tee /etc/compose-cd/config
+	echo -e "SEARCH_ROOT=\"${search_root}\"\n\nGIT_PULL_USER=\"${git_pull_user}\"\n\nDISCORD_WEBHOOK=\"${discord_webhook}\"" | tee /etc/compose-cd/config
 
 	load_global_config
 	notify "notify test" "[test] "
